#!/bin/sh
#
# NodeWatcher configuration
# 

netmon_api="[fe80::201:2ff:fe03:405%br-mesh]"

autoupdate="y"

router_update_by_id="n"
router_id="yournodeid"
nickname="yourickname"
password="yourpassword"

router_auto_assign="y"
router_auto_update_hash=" " #Space for no Hash!!!