#!/bin/sh
#
# NodeWatcher wrapper
# 

update() {
	echo "Suche neue Version"
	command="wget -q -O - http://$netmon_api/api_nodewatcher.php?section=version"
	available_version=`$command`

	script_version=`$SCRIPT_DIR/nodewatcher_script "version"`

	if [[ $available_version != $script_version ]]; then
		echo "Eine neue Version ist Verfügbar, script wird geupdated"
		wget -q -O $SCRIPT_DIR/nodewatcher_script http://$netmon_api/api_nodewatcher.php?section=update
	else
		echo "Das Script ist aktuell"
	fi
}

LANG=C

SCRIPT_DIR=`dirname $0`
. $SCRIPT_DIR/nodewatcher_config

if [[ $autoupdate == "y" ]]; then
	echo "Autoupdate ist an"
	update
else
	echo "Autoupdate ist aus"
fi

if [[ "$1" == "update" ]]; then
	echo "Führe manuelles update aus"
	update
fi

echo "Prüfe Authentifizierungsmethode"
if [ $router_update_by_id == "y" ]; then
	echo "Authentifizierungsmethode ist: Username und Passwort"
	authentificationmethod="user"
elif [ $router_auto_assign == "y" ]; then
	echo "Authentifizierungsmethode ist: Autoassign und Hash"
	authentificationmethod="hash"
	echo "Prüfe ob Roter schon mit Netmon verknüpft ist"
echo $router_auto_update_hash
	if [ "$router_auto_update_hash" == " " ]; then
		echo "Der Router ist noch NICHT mit Netmon verknüpft"
		echo "Versuche verknüpfung herzustellen"

		#try to get mac adress for auto assign
		router_auto_assign_login_string=$(ifconfig br-mesh | grep HWaddr | awk '{ print $5 }'|sed -e 's/://g')
		if [ "$router_auto_assign_login_string" == "" ]; then
			router_auto_assign_login_string=$(ifconfig eth0 | grep HWaddr | awk '{ print $5 }'|sed -e 's/://g')
		fi
		
		if [ "$router_auto_assign_login_string" == "" ]; then
			router_auto_assign_login_string=$(ifconfig ath0 | grep HWaddr | awk '{ print $5 }'|sed -e 's/://g')
		fi

		if [ "$router_auto_assign_login_string" == "" ]; then
			echo "Cannot get router_auto_assign_login_string from interface mac adress"
		else

	#		hostname="`cat /proc/sys/kernel/hostname`"
			command="wget -q -O - http://$netmon_api/api_nodewatcher.php?section=router_auto_assign&router_auto_assign_login_string=$router_auto_assign_login_string"
			echo "$command"
			ergebnis=`$command`
			
			if [ "${ergebnis/error}" == "$ergebnis" ]; then
				router_auto_update_hash=`echo $ergebnis| cut '-d;' -f2`
				router_id=`echo $ergebnis| cut '-d;' -f1`
				hostname=`echo $ergebnis| cut '-d;' -f3`
			
#write new config
cat > $SCRIPT_DIR/nodewatcher_config <<EOF
autoupdate="$autoupdate"

netmon_api="$netmon_api"

router_update_by_id="$router_update_by_id"
router_id="$router_id"
nickname="$nickname"
password="$password"
router_auto_assign="$router_auto_assign"
router_auto_update_hash="$router_auto_update_hash"
EOF

				echo "Der Router wurde mit Netmon verknüpft"

				echo "Hostname wird konfiguriert"
				uci set system.@system[0].hostname=$hostname
				uci commit
				echo $hostname > /proc/sys/kernel/hostname
				echo "Hostname wurde konfiguriert"


			else
				echo "es ist ein fehler aufgetreten"
				echo $ergebnis
			fi
		fi
	else
		echo "Der Router ist bereits mit Netmon verknüpft"
	fi
fi

echo "Sende aktuelle Statusdaten"
$SCRIPT_DIR/nodewatcher_script "crawl" "$netmon_api" "$router_id" "$nickname" "$password" "$authentificationmethod" "$router_auto_update_hash"