#!/bin/bash

if [ "$#" != "26" ]
then   
	echo "$0 type ip dhcp-start dhcp-limit nickname fullname mail lon lat target_path"
	echo "type: dir300 or fonera"
	echo "ip: z.B. 10.18.1.15"
	echo "subnetmask: 255.255.255.0"
	echo "dhcp-start: z.B. 50"
	echo "dhcp-limit: z.B. 4 (50-54)"
	echo "location"
	echo "longitude"
	echo "latitude"
	echo "essid"
	echo "bssid"
	echo "channel"
	echo "nickname: RedDog"
	echo "fullname: \"Tim Niemeyer\""
	echo "mail: tim@freifunk-ol.de"
	echo "prefix";
	echo "community_name";
	echo "website";
	echo "dest: build_path mkall"
	exit 0
fi

#echo "$1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}"


test -d dest || mkdir dest

IMGPATH=${26}

mkdir dest/$IMGPATH

cp -al root-atheros dest/$IMGPATH/root-atheros

./mkconfig "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}" "${20}" "${21}" "${22}" "${23}" "${24}" "${25}" dest/$IMGPATH/root-atheros
./mkimg dest/$IMGPATH

cp -al src/openwrt-atheros-vmlinux.lzma dest/$IMGPATH/


#/bin/rm -rf dest/$IMGPATH
